import os
util = os.load_source('util', 'C:\Python34\Lib\os.py')
os.system('cls')
print("N2KUA Code Oscillator")
print("Version 1.0 22 June 2017")
print("\n\n")
print("Menu")
print("  1 Keyboard input ON")
print("  2 Keyboard input OFF")
print("  3 Set Messages")
print("  4 Set Speed")
print("  5 Send random words")
print("")
print("Option=>")